# Generated by Django 5.0.1 on 2024-01-24 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
